    'print("hello" and 3)',
    'print(True + 1)',
    'print(5 < "x")',
    'x = 5 < "x"',
    'print(not "hello")',
    'print(5 and None)',
    'print("x" or False)',
    'print("a" < 5)',
    'print(1 / 0)',
    'print("a" + 5)',
    'print(undefined_var)',
    'x = 10 + "x"',
    'y = True - False',
    'print("a" * "b")',
    'print(3 > None)',
    'z = None < 4',
    'print(True and "string") + 1'